name: CI

on:
  push:
    branches:
      - master

jobs:
  publish-pilet:
    name: Build and Deploy
    runs-on: [ubuntu-16.04]
    steps:
    - uses: actions/checkout@master
    - name: Publish Pilet
      uses: smapiot/publish-pilet-action@v1
      with:
        feed: sample
        api-key: ${{ secrets.apiKey }}
